// <auto-generated />
using System;
using BookStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStore.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20200610140104_Add_Table_Menu")]
    partial class Add_Table_Menu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BookStore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnName("author")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("varchar(1000)")
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<float>("DiscountedPrice")
                        .HasColumnName("discountedPrice")
                        .HasColumnType("float(11,0)");

                    b.Property<float>("Price")
                        .HasColumnName("price")
                        .HasColumnType("float(11,0)");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("book");
                });

            modelBuilder.Entity("BookStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<int?>("Parentid")
                        .HasColumnName("parentid")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("BookStore.Models.Categorybook", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("bookId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnName("categoryId")
                        .HasColumnType("int");

                    b.HasKey("BookId")
                        .HasName("PRIMARY");

                    b.HasIndex("CategoryId")
                        .HasName("FK_CategoryBook_Category");

                    b.ToTable("categorybook");
                });

            modelBuilder.Entity("BookStore.Models.Menu", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<int?>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("order")
                        .HasColumnType("int(11)")
                        .HasDefaultValue(0);

                    b.Property<int?>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("parentId")
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("title")
                        .HasColumnType("varchar(200)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("menu");
                });

            modelBuilder.Entity("BookStore.Models.Categorybook", b =>
                {
                    b.HasOne("BookStore.Models.Book", "Book")
                        .WithOne("Categorybook")
                        .HasForeignKey("BookStore.Models.Categorybook", "BookId")
                        .HasConstraintName("FK_CategoryBook_Book")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Models.Category", "Category")
                        .WithMany("Categorybook")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_CategoryBook_Category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Models.Menu", b =>
                {
                    b.HasOne("BookStore.Models.Menu", "Parent")
                        .WithMany("ChildMenus")
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
